version: '3.4'
services:
  #####################
  #### NODE SERVICE
  #####################
  microservice.cote.io:
    build: .
    container_name: node
    restart: unless-stopped
    image: microservice/node
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - microservice-network

  product-service:
    extends: microservice.cote.io
    command: node services/service.product.js

  order-service:
    extends: microservice.cote.io
    command: node services/service.product.js

  monitor-service:
    extends: microservice.cote.io
    command: node services/service.monitor.js

  #####################
  #### NGINX SERVICE
  #####################
  proxy:
    container_name: nginx
    restart: unless-stopped
    image: nginx:alpine
    depends_on:
      - microservice.cote.io
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf/etc/nginx/conf.d/default.conf
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
