version: '3.4'
services:
  #####################
  #### API SERVICE
  #####################
  microservice.cote.io:
    build: .
    restart: unless-stopped
    container_name: api-service
    image: microservice/api-service
    environment:
      - MONGO_URI=mongodb://localhost:27010/microservice
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    networks:
      - microservice-network

  #####################
  #### PRODUCT SERVICE
  #####################
  product-service:
    build: .
    restart: unless-stopped
    container_name: product-service
    image: microservice/product-service
    command: node services/service.product.js
    volumes:
      - ./services/service.product.js:/usr/src/app
    networks:
      - microservice-network

  #####################
  #### ORDER SERVICE
  #####################
  order-service:
    build: .
    restart: unless-stopped
    container_name: order-service
    image: microservice/order-service
    command: node services/service.order.js
    volumes:
      - ./services/service.order.js:/usr/src/app
    networks:
      - microservice-network

  #####################
  #### MONITOR SERVICE
  #####################
  monitor-service:
    build: .
    container_name: monitor-service
    restart: unless-stopped
    image: microservice/monitor-service
    command: node services/service.monitor.js
    volumes:
      - ./services/monitor.order.js:/usr/src/app
    ports:
      - 5000:5000

  #####################
  #### NGINX SERVICE
  #####################
  proxy:
    container_name: nginx
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - microservice.cote.io
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservice-network

  #####################
  #### MONGODB SERVICE
  #####################
  db:
    container_name: mongodb
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=microservice
    ports:
      - 27010:27017
    volumes:
      - db:/var/lib/mongodb/data
    networks:
      - microservice-network

volumes:
  db:

networks:
  microservice-network:
    driver: bridge
